Students = [
    {
        "id": 1,
        "first_name": "Abijuru",
        "last_name": "Raissa",
        "email": "abijururaissa@gmail.com",
        "faculty": "Information Technolgy",
        "department": "software Engineering",
        "level": 3,
        "cgpa": 2.89,
    },
    {
        "id": 2,
        "first_name": "Ineza",
        "last_name": "Revocate",
        "email": "inezaroxy@gmail.com",
        "faculty": "Information Technolgy",
        "department": "software Engineering",
        "level": 2,
        "cgpa": 2.16,
    },
    {
        "id": 3,
        "first_name": "Bayizere",
        "last_name": "Marius",
        "email": "bayizeremarius@gmail.com",
        "faculty": "Information Technolgy",
        "department": "software Engineering",
        "level": 3,
        "cgpa": 3.20,
    },
    {
        "id": 4,
        "first_name": "Hirwe",
        "last_name": "Valantine",
        "email": "valantinehirwe@gmail.com",
        "faculty": "Information Technolgy",
        "department": "Information Management",
        "level": 3,
        "cgpa": 3.50,
    },
    {
        "id": 5,
        "first_name": "Niyigena",
        "last_name": "Jeanne",
        "email": "jeanne@gmail.com",
        "faculty": "Information Technolgy",
        "department": "software Engineering",
        "level": 3,
        "cgpa": 2.70,
    },
]
